import { useState, useRef } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { X, FileText, Check, Download, Shield } from 'lucide-react'
import { supabase } from '@/lib/supabase'
import { useAuth } from '@/context/AuthContext'
import toast from 'react-hot-toast'

const DEALMATCH_WHATSAPP = '2347057392060'

const COMMISSION_RATES = {
  sale:     { rate: 1.5,  label: '1.5% of final sale price' },
  rental:   { rate: 3,    label: '3% of first year total rent' },
  shortlet: { rate: 8,    label: '8% per booking' },
  hotel:    { rate: 8,    label: '8% per booking' },
}

function generateAgreementText({ property, buyer, date, category, customTerms }) {
  const commission = COMMISSION_RATES[category] || COMMISSION_RATES.sale
  return `
DEALMATCH PROPERTY TRANSACTION AGREEMENT
════════════════════════════════════════

Agreement Reference: DM-${Date.now()}
Date: ${date}
Platform: DealMatch (dealmatch-yvdm.vercel.app)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PARTIES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Buyer / Renter / Guest:
  Name:  ${buyer.name}
  Email: ${buyer.email}
  Phone: ${buyer.phone || 'Provided on platform'}

Property:
  Title:    ${property.title}
  Location: ${property.city}, ${property.state}
  Price:    ₦${Number(property.price).toLocaleString()}${property.price_period ? ' per ' + property.price_period : ''}
  Listed by: ${property.landlord_name || 'Verified Lister'}

Facilitator:
  DealMatch Property Platform
  Contact: +234 705 739 2060
  Website: dealmatch-yvdm.vercel.app

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TERMS OF TRANSACTION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. PLATFORM ROLE
   DealMatch acts as a facilitator connecting buyers and sellers/landlords.
   All transactions are coordinated through the DealMatch platform.

2. COMMISSION
   A success commission of ${commission.label} is payable to DealMatch
   upon successful completion of this transaction.
   Commission is paid via Paystack before final handover or key exchange.

3. CONTACT DISCLOSURE
   Contact details of the lister are revealed to the buyer only after:
   a) This agreement is digitally accepted by the buyer
   b) DealMatch has been notified of the transaction intent
   c) Commission payment has been arranged

4. NO BYPASS CLAUSE
   Both parties agree NOT to conduct this transaction outside the DealMatch
   platform. Any attempt to bypass DealMatch after initial introduction
   constitutes a breach of this agreement and the commission remains payable.

5. AUTHENTICITY
   Both parties confirm they are real individuals with valid identity.
   Listings and enquiries made under false pretences are grounds for
   immediate account suspension.

6. DISPUTE RESOLUTION
   Any disputes arising from this transaction shall be first mediated
   by DealMatch. Unresolved disputes may be escalated to appropriate
   Nigerian legal authorities.

${customTerms ? `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
LISTER'S CUSTOM TERMS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${customTerms}

` : ''}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
DIGITAL ACCEPTANCE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

By signing below, the buyer confirms they have read, understood,
and agreed to all terms in this agreement.

Buyer Signature: _______________________________
Full Name:       ${buyer.name}
Date:            ${date}
Platform ID:     ${buyer.id || 'Authenticated User'}

This agreement is legally binding under Nigerian contract law.
Generated by DealMatch · ${date}
  `.trim()
}

// ─── Main DealAgreement Modal ──────────────────────────────
export default function DealAgreement({ property, category = 'sale', onClose, onAccepted }) {
  const { user, profile } = useAuth()
  const [step, setStep]         = useState('review') // review | sign | success
  const [agreed, setAgreed]     = useState(false)
  const [signature, setSignature] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [phone, setPhone]       = useState(profile?.phone || '')

  const date = new Date().toLocaleDateString('en-NG', {
    year:'numeric', month:'long', day:'numeric'
  })

  const buyer = {
    name:  profile?.full_name || user?.user_metadata?.full_name || 'Buyer',
    email: user?.email || '',
    phone: phone,
    id:    user?.id,
  }

  const agreementText = generateAgreementText({
    property,
    buyer,
    date,
    category,
    customTerms: property.custom_terms || property.rules || null,
  })

  const downloadAgreement = () => {
    const blob = new Blob([agreementText], { type: 'text/plain' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href     = url
    a.download = `DealMatch-Agreement-${property.title?.replace(/\s+/g,'-')}-${Date.now()}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  const handleSign = async () => {
    if (!agreed) return toast.error('Please check the agreement box')
    if (!signature || signature.trim().length < 3) return toast.error('Please type your full name as signature')
    if (!phone) return toast.error('Please add your phone number')

    setSubmitting(true)

    // Save agreement record to Supabase
    const { error } = await supabase.from('deal_agreements').insert({
      property_id:    property.id,
      buyer_id:       user.id,
      buyer_name:     buyer.name,
      buyer_email:    buyer.email,
      buyer_phone:    phone,
      buyer_signature:signature,
      agreement_text: agreementText,
      category:       category,
      status:         'buyer_signed',
      created_at:     new Date().toISOString(),
    }).select().single()

    // Notify DealMatch via WhatsApp regardless of DB error
    const msg = encodeURIComponent(
      `🔔 *New Deal Agreement Signed — DealMatch*\n\n` +
      `Property: *${property.title}*\n` +
      `Location: ${property.city}, ${property.state}\n` +
      `Price: ₦${Number(property.price).toLocaleString()}${property.price_period ? '/'+property.price_period : ''}\n` +
      `Category: ${category.toUpperCase()}\n\n` +
      `Buyer: ${buyer.name}\n` +
      `Email: ${buyer.email}\n` +
      `Phone: ${phone}\n\n` +
      `✅ Agreement signed. Please connect both parties and arrange commission payment.`
    )

    setSubmitting(false)
    setStep('success')

    // Open WhatsApp notification to DealMatch
    setTimeout(() => {
      window.open(`https://wa.me/${DEALMATCH_WHATSAPP}?text=${msg}`, '_blank')
    }, 1000)

    onAccepted?.({
      buyer,
      agreement: agreementText,
      signed_at: new Date().toISOString(),
    })
  }

  return (
    <div className="fixed inset-0 z-50 flex items-end md:items-center justify-center p-4"
      style={{backgroundColor:'rgba(26,18,16,0.85)', backdropFilter:'blur(8px)'}}
      onClick={e => e.target === e.currentTarget && onClose()}>

      <motion.div initial={{opacity:0, y:40}} animate={{opacity:1, y:0}} exit={{opacity:0, y:40}}
        className="w-full max-w-lg rounded-3xl overflow-hidden flex flex-col"
        style={{backgroundColor:'#FFFAF5', maxHeight:'90vh'}}>

        {/* Header */}
        <div className="flex items-center justify-between p-5 border-b flex-shrink-0"
          style={{borderColor:'#E8DDD2'}}>
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl flex items-center justify-center"
              style={{backgroundColor:'rgba(201,106,58,0.1)'}}>
              <FileText size={18} style={{color:'#C96A3A'}} />
            </div>
            <div>
              <h3 className="font-display text-lg font-black" style={{color:'#1A1210'}}>
                Transaction Agreement
              </h3>
              <p className="text-xs" style={{color:'#8A7E78'}}>{property.title}</p>
            </div>
          </div>
          <button onClick={onClose} className="w-8 h-8 rounded-full flex items-center justify-center"
            style={{backgroundColor:'rgba(26,18,16,0.08)'}}>
            <X size={14} style={{color:'#5C4A3A'}} />
          </button>
        </div>

        {/* Content */}
        <div className="overflow-y-auto flex-1">

          {step === 'review' && (
            <div className="p-5">
              {/* Why this exists */}
              <div className="p-4 rounded-2xl mb-5 flex items-start gap-3"
                style={{backgroundColor:'rgba(122,158,126,0.08)', border:'1px solid rgba(122,158,126,0.2)'}}>
                <Shield size={16} style={{color:'#7A9E7E', flexShrink:0, marginTop:2}} />
                <div>
                  <p className="text-xs font-bold mb-1" style={{color:'#5C8060'}}>
                    Why this agreement?
                  </p>
                  <p className="text-xs leading-relaxed" style={{color:'#8A7E78'}}>
                    This protects you as a buyer and ensures every transaction on DealMatch is recorded. After signing, DealMatch will connect you with the lister and arrange the next steps.
                  </p>
                </div>
              </div>

              {/* Agreement preview */}
              <div className="rounded-2xl p-4 mb-5 font-mono text-xs leading-relaxed overflow-y-auto"
                style={{
                  backgroundColor:'rgba(26,18,16,0.03)',
                  border:'1px solid #E8DDD2',
                  maxHeight: 300,
                  color:'#5C4A3A',
                  whiteSpace:'pre-wrap',
                }}>
                {agreementText}
              </div>

              <div className="flex gap-3">
                <button onClick={downloadAgreement}
                  className="flex items-center gap-2 px-4 py-3 rounded-2xl text-sm font-semibold border transition-all"
                  style={{borderColor:'#E8DDD2', color:'#5C4A3A', backgroundColor:'#FFFFFF'}}>
                  <Download size={14} /> Download
                </button>
                <button onClick={() => setStep('sign')}
                  className="flex-1 btn-primary py-3 text-sm">
                  Proceed to Sign →
                </button>
              </div>
            </div>
          )}

          {step === 'sign' && (
            <div className="p-5 space-y-4">
              <div>
                <h4 className="font-display font-black text-lg mb-1" style={{color:'#1A1210'}}>
                  Sign the Agreement ✍️
                </h4>
                <p className="text-sm" style={{color:'#8A7E78'}}>
                  Type your full name as your digital signature and confirm your phone number.
                </p>
              </div>

              <div>
                <label className="text-xs font-bold uppercase tracking-wider mb-2 block" style={{color:'rgba(26,18,16,0.5)'}}>
                  Your Phone Number *
                </label>
                <input className="input" type="tel" placeholder="+234 800 000 0000"
                  value={phone} onChange={e => setPhone(e.target.value)}
                  style={{backgroundColor:'#FFFFFF', color:'#1A1210'}} />
              </div>

              <div>
                <label className="text-xs font-bold uppercase tracking-wider mb-2 block" style={{color:'rgba(26,18,16,0.5)'}}>
                  Digital Signature — Type your full name *
                </label>
                <input className="input font-display text-lg" type="text"
                  placeholder="e.g. John Adebayo Okafor"
                  value={signature} onChange={e => setSignature(e.target.value)}
                  style={{backgroundColor:'#FFFFFF', color:'#1A1210', fontStyle:'italic'}} />
                <p className="text-xs mt-1" style={{color:'#8A7E78'}}>
                  This acts as your legally binding digital signature
                </p>
              </div>

              {/* Agreement checkbox */}
              <label className="flex items-start gap-3 cursor-pointer p-4 rounded-2xl border-2 transition-all"
                style={{
                  borderColor: agreed ? '#C96A3A' : '#E8DDD2',
                  backgroundColor: agreed ? 'rgba(201,106,58,0.04)' : '#FFFFFF',
                }}>
                <div className="mt-0.5 w-5 h-5 rounded-md border-2 flex items-center justify-center flex-shrink-0 transition-all"
                  style={{
                    borderColor: agreed ? '#C96A3A' : '#E8DDD2',
                    backgroundColor: agreed ? '#C96A3A' : '#FFFFFF',
                  }}
                  onClick={() => setAgreed(!agreed)}>
                  {agreed && (
                    <svg width="10" height="8" viewBox="0 0 10 8" fill="none">
                      <path d="M1 4L3.5 6.5L9 1" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                    </svg>
                  )}
                </div>
                <p className="text-sm leading-relaxed" style={{color:'#1A1210'}}>
                  I have read and agree to all terms in this agreement. I understand that DealMatch will facilitate this transaction and that commission is payable upon successful completion.
                </p>
              </label>

              <div className="flex gap-3">
                <button onClick={() => setStep('review')}
                  className="px-4 py-3 rounded-2xl text-sm font-semibold border"
                  style={{borderColor:'#E8DDD2', color:'#8A7E78', backgroundColor:'#FFFFFF'}}>
                  ← Back
                </button>
                <button onClick={handleSign}
                  disabled={submitting || !agreed || signature.trim().length < 3}
                  className="flex-1 py-3 rounded-2xl text-sm font-semibold transition-all"
                  style={{
                    backgroundColor: agreed && signature.trim().length >= 3 ? '#C96A3A' : 'rgba(26,18,16,0.1)',
                    color: agreed && signature.trim().length >= 3 ? '#FFFFFF' : '#8A7E78',
                  }}>
                  {submitting ? 'Submitting...' : 'Sign & Submit Agreement ✓'}
                </button>
              </div>
            </div>
          )}

          {step === 'success' && (
            <div className="p-8 text-center">
              <motion.div initial={{scale:0}} animate={{scale:1}} transition={{type:'spring', stiffness:200}}>
                <div className="text-6xl mb-4">🎉</div>
              </motion.div>
              <h3 className="font-display font-black text-2xl mb-2" style={{color:'#1A1210'}}>
                Agreement Signed!
              </h3>
              <p className="text-sm leading-relaxed mb-2" style={{color:'#8A7E78'}}>
                DealMatch has been notified and will contact you within 24 hours to connect you with the lister and arrange the next steps.
              </p>
              <p className="text-xs font-semibold mb-6" style={{color:'#C96A3A'}}>
                Check your WhatsApp — a confirmation has been sent to DealMatch.
              </p>

              <div className="p-4 rounded-2xl mb-6 text-left"
                style={{backgroundColor:'rgba(201,106,58,0.06)', border:'1px solid rgba(201,106,58,0.15)'}}>
                <p className="text-xs font-bold uppercase tracking-wider mb-2" style={{color:'rgba(26,18,16,0.4)'}}>What happens next</p>
                <div className="space-y-1.5 text-xs" style={{color:'#5C4A3A'}}>
                  <p>1️⃣ DealMatch reviews your signed agreement</p>
                  <p>2️⃣ Lister is notified and countersigns</p>
                  <p>3️⃣ Contact details are shared with both parties</p>
                  <p>4️⃣ Commission is arranged via Paystack before handover</p>
                </div>
              </div>

              <button onClick={downloadAgreement}
                className="flex items-center justify-center gap-2 w-full py-3 rounded-2xl text-sm font-semibold border mb-3"
                style={{borderColor:'#E8DDD2', color:'#5C4A3A', backgroundColor:'#FFFFFF'}}>
                <Download size={14} /> Download Your Copy
              </button>
              <button onClick={onClose} className="btn-primary w-full py-3 text-sm">
                Done
              </button>
            </div>
          )}
        </div>
      </motion.div>
    </div>
  )
}
